Fix free
fe7ch/cowrie pull request #17
Opened 2021-12-20 17:58 UTC by gglchrm

2021-12-20 18:27 UTC, crazylazyowl requested changes

2021-12-20 18:27 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +class command_free(HoneyPotCommand):
`Command_free`

2021-12-20 18:27 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +    def _total(self, meminfo: Dict[str, int]) -> None:
Давай назовём `_print_total_stats`?

2021-12-20 18:27 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +        magnitude = ["B", "M", "G", "T", "Z"]
Можно сделать через tulpe (неизменяемый тип) и вынести в классовую переменную
```
MAGNITUDE = ("B", ...)
```

2021-12-20 18:27 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +                value //= 1024
С `--human`  флагом выводятся float значения
Можно так переписать
```
for key in meminfo:
    index = 0
    value = float(meminfo[key])
    while ...
        value /= 1024
```

2021-12-20 18:27 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +            self._total(meminfo)
Здесь есть проблема в том, что `-t` сочетается со всеми другими опциями `-m, -h, --tera и т.д`

2021-12-20 18:27 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +            self._total(meminfo)
Т.е, наверное, `_total` стоит сделать, как опцию для `print_stats_for_human` и `print_stats`

2021-12-20 18:27 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +        "-/+ buffers/cache\n"
После buffers/cache идут числа соответвующие одному и второму

2021-12-20 18:27 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +    MEMINFO_KEYS = ["MemTotal", "MemFree", "Shmem", "Buffers", "Cached", "SwapTotal", "SwapFree"]
Можно через tuple сделать

2021-12-20 18:27 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +            opts, args = getopt.getopt(self.args, "hbkmgVt",
Можно поаккуратнее оформить
```
opts, args = getopt.getopt(
    self.args, "hbkmgVt", ["human", ...])
```
Т.е. перенос строки иначе сделать, но это хотелка

2021-12-20 18:27 UTC, crazylazyowl commented on src/cowrie/commands/free.py
>      def call(self):
`-> None`

2021-12-20 18:27 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +                self._print_stats(meminfo, fmt="kilo")
`fmt="kilo"` можно убрать, т.к. дефолтное значение

2021-12-20 18:30 UTC, crazylazyowl requested changes

2021-12-20 18:30 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +from __future__ import absolute_import, division
Как будто бы, здесь как раз нужно
```
from __future__ import annotations
```
`absolute_import, division` вроде для 2х питона нужны, а его мы уже не поддеживаем.
Чёт надо поразбираться.

2021-12-20 18:43 UTC, gglchrm commented on src/cowrie/commands/free.py
> +            self._total(meminfo)
Думала о том, чтобы сделать отдельный шаблон для `--total` и вызывать, например, когда есть необходимость. Как `OUTPUT_FMT`, только `OUTPUT_FMT_TOTAL`. И тогда в `format()` можно передавать`meminfo[key]` прям там складывая их. Что думаешь?

2021-12-20 18:47 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +            self._total(meminfo)
Да, можно и так сделать.
Можно в `_read_stats` добавить аргумент `total: bool = False` и там подсчитывать значения, если `True`
```
if total:
    meminfo["..."] = ...
```

2021-12-20 19:05 UTC, gglchrm commented on src/cowrie/commands/free.py
> +                self._print_stats(meminfo, fmt="kilo")
Я не стала бы убирать, может упасть при запросе. Пока в Usage есть пусть будет, что скажешь?

2021-12-20 19:12 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +                self._print_stats(meminfo, fmt="kilo")
почему может упасть?... в объявлении функции `_print_stats` прописано дефолтное значение для `fmt`

2021-12-20 19:35 UTC, gglchrm commented on src/cowrie/commands/free.py
> +                value //= 1024
Сыплется на тестах
```src/cowrie/commands/free.py:113:21: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
src/cowrie/commands/free.py:115:17: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]```

2021-12-20 19:35 UTC, gglchrm commented on src/cowrie/commands/free.py
> +                value //= 1024
`src/cowrie/commands/free.py:113:21: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]`
`src/cowrie/commands/free.py:115:17: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]`

2021-12-20 19:53 UTC, crazylazyowl requested changes

2021-12-20 19:53 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +            tmp[key] = "{:g}{}".format(round(value, 1), self.MAGNITUDE[index])
Лучше через имя класса, а не `self.` обращаться  к классовым переменным. Просто понятнее...
```
tmp[key] = "{:g}{}".format(round(value, 1), Command_free.MAGNITUDE[index])
```

2021-12-20 19:53 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +                value /= 1024.0
`.0` можно убрать

2021-12-20 19:53 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +            while value >= 1024.0 and index < len(self.MAGNITUDE):
`self.` -> `Command_free.`

2021-12-20 19:53 UTC, crazylazyowl commented on src/cowrie/commands/free.py
>          for key, value in meminfo.items():
`value` можно убрать, ты его потом через `meminfo[key]` получаешь

2021-12-20 19:54 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +            tmp[key] = "{:g}{}".format(round(value, 1), self.MAGNITUDE[index])
А то куришь иногда чей-то код и там `self....`, а выясняется, что либо статик метод, либо классовый. И мягко говоря, не очень прикольно.

2021-12-20 19:56 UTC, crazylazyowl commented on src/cowrie/commands/free.py
>          for key, value in meminfo.items():
и ошибка должна будет исчезнуть
у тебя изначально `value` - int, а потом ты решаешь в `value` перезапихнуть float
вот mypy и бесится

2021-12-21 14:53 UTC, gglchrm commented on src/cowrie/commands/free.py
>          for key, value in meminfo.items():
Проблема, может, исчезнет, но 
            total       used       free     shared    buffers     cached
Mem:    4.05474e+06G 3.057e+06G    997740M     49908M     40276M 1.80186e+06G
-/+ buffers/cache      40276M 1.80186e+06G
Swap:   2.09715e+06G     70632M 2.02652e+06G
Total:  6.15189e+06G 3.12764e+06G 3.02426e+06G

2021-12-21 15:02 UTC, gglchrm commented on src/cowrie/commands/free.py
>          for key, value in meminfo.items():
я же явно указываю, что он ругается. проблема осталась, буду решать.

2021-12-21 20:09 UTC, crazylazyowl requested changes

2021-12-21 20:09 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +            totalinfo = {
Хм... Вот у тебя есть три метода `print_stats`, `print_stats_for_human` и `read_meminfo`. 
Первые два начинаются с `print_`, следовательно, от них ты **ожидаешь** только то, что они красиво выведут на экран нужную информацию.
И есть метод `read_meminfo`, от которого **ожидаешь** получение нужной информации (читает `/proc/meminfo`, что-то там вычисляет).

Сейчас же на метод `print_` возложены две задачи: 
- подсчитать какие-то числа
- красиво напечатать

Может стоит все вычисления (т.е. формирование нужных данных) вынести в `read_meminfo`, а в `print_`'ах только красиво на экран печатать?

2021-12-21 20:09 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +        if total:
Просто придирка, но... в одном случае ты пишешь `if total: ...`, в другом `if not total: ...`. Можно везде написать одинаково.

2021-12-21 20:09 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +        "Total:  {TotalTotal:>10} {TotalUsed:>10} {TotalFree:>10}\n"
Наверное, можно сделать `OUTPUT_FMT`, который содержит первые 4 строки
```
    OUTPUT_TOTAL_FMT = (
        "             total       used       free     shared    buffers     cached\n"
        "Mem:    {MemTotal:>10} {MemUsed:>10} {MemFree:>10} {Shmem:>10} {Buffers:>10} {Cached:>10}\n"
        "-/+ buffers/cache  {Buffers:>10} {Cached:>10}\n"
        "Swap:   {SwapTotal:>10} {SwapUsed:>10} {SwapFree:>10}\n"
```

И отдельно `TOTAL_FMT`, которая будет содержать **только** дополнительную строку
```
        "Total:  {TotalTotal:>10} {TotalUsed:>10} {TotalFree:>10}\n"
```
Так будет проще вносить правки, если в будующем что-то придётся менять.

2021-12-23 12:39 UTC, gglchrm commented on src/cowrie/commands/free.py
> +            totalinfo = {
Звучит оч здраво, продолжая твою логику предложу разнести на 3 функционала:
- чтение
- форматирование
- запись

И тогда получится `read_meminfo`, `human_format`, `magniture_format` и `print_output`. Что скажешь?

2021-12-23 12:41 UTC, gglchrm commented on src/cowrie/commands/free.py
> +        "Total:  {TotalTotal:>10} {TotalUsed:>10} {TotalFree:>10}\n"
В принципе почему бы и нет, всё равно она в самом низу идёт, "допечатать" её если `total = True` не должно составить труда.

2021-12-23 12:43 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +            totalinfo = {
Можно попробовать

2021-12-23 14:56 UTC, crazylazyowl requested changes

2021-12-23 14:56 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +        if total:
Раз и ...

2021-12-23 14:56 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +        if total:
... два.

Вынеси этот `if total: meminfo[..] = ...`  в read_meminfo

2021-12-23 14:56 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +    def _print_output(self, dict, total=False):
`dict` писать плохо (и IDE должна была подсказать), поэтому что это ключевое слово для python

и про типы забыла
`def _print_output(self, meminfo: Dict[str, Union[int, float]], total: bool = False) -> None:`

2021-12-23 14:56 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +        union = {**meminfo, **totalinfo}
Уберёшь код в `_read_meminfo` и `union` должен будет исчезнуть

2021-12-23 14:56 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +        if "--total" in tmp or "-t" in tmp:
Можно короче записать
`total = True if "--total" in tmp or "-t" in tmp else False`
вроде, даже так сработает
`total = "--total" in tmp or "-t" in tmp`

2021-12-23 20:18 UTC, crazylazyowl requested changes

2021-12-23 20:18 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +            self._magniture_format(meminfo, total=total)
Этого раньше здесь не было... Откуда взялось и зачем?

2021-12-23 20:18 UTC, crazylazyowl commented on src/cowrie/commands/free.py
> +        elif fmt == "kilo":
Этого тоже не было... Почему и зачем?

2021-12-27 15:50 UTC, gglchrm commented on src/cowrie/commands/free.py
> +            self._magniture_format(meminfo, total=total)
Чего именно не было?

2022-01-12 10:47 UTC, gglchrm commented on src/cowrie/commands/free.py
> +        union = {**meminfo, **totalinfo}
Так и случилось)

2022-01-12 10:47 UTC, gglchrm commented on src/cowrie/commands/free.py
> +        elif fmt == "kilo":
йа не очень понимаю о чём ты

2022-01-13 16:16 UTC, crazylazyowl approved these changes

2022-01-21 21:32 UTC, fe7ch approved these changes

2022-01-21 21:32 UTC, merged