Fix etcinitd iptables
fe7ch/cowrie pull request #6
Opened 2021-12-15 15:31 UTC by gglchrm

Пока не нашла способа доставать имя полученной команды пусть будет так. За последние 3 месяца на ханипоты '/etc/init.d' приходил только как '/etc/init.d/iptables stop'. Предлагаю оставить это как решение до появления других вариаций.

2021-12-15 15:44 UTC, crazylazyowl commented
Вообще, была мысль фиксить это на манер https://github.com/fe7ch/cowrie/commit/5d3aa1a3ca206055234e63dafee515087f82ca4f...

По идее, обращение напрямую к `/etc/init.d/<service_name> <cmd>` равносильно вызову нормальной команды `service <service_name> <cmd>`. Следовательно, фикс можно было бы вкорячить в `lineRecieved`, т.е. `/etc/init.d/<service_name> <cmd>` преобразовывать в `/etc/init.d <service_name> <cmd>`. И в `../commands/service` добавить `commands["/etc/init.d"] = Command_service`.

Получится не оч красивое, но, как будто бы, более общее решение...

2021-12-15 15:56 UTC, gglchrm commented
Полностью одобряю и уважаю подход делать более общие решения.

[5d3aa1a](https://github.com/fe7ch/cowrie/commit/5d3aa1a3ca206055234e63dafee515087f82ca4f) -- круто, дико конечно, но работает. Я попробую сделать так. Могут быть проблемы с некорректнымм выводом, но я постараюсь по максимуму их избежать.

2021-12-15 15:57 UTC, crazylazyowl commented
Если принимать текущую реализацию (не рассматривать мою идею), то надо запилить тесты...

2021-12-16 13:06 UTC, crazylazyowl requested changes

2021-12-16 13:06 UTC, crazylazyowl commented on src/cowrie/test/xaa
> +[A[B
Это явно что-то лишнее...

2021-12-16 13:06 UTC, crazylazyowl commented on src/cowrie/commands/__init__.py
> +    "etc_init_d",
Надо выпилить

2021-12-16 13:06 UTC, crazylazyowl commented on src/cowrie/commands/etc_init_d.py
> +commands["/etc/init.d/iptables"] = Command_etc_init_d
Файл целиком надо убрать

2021-12-16 13:06 UTC, crazylazyowl commented on src/cowrie/shell/honeypot.py
> +        r = re.search(r"\/etc\/init\.d\/", line)
Испльзование `re.` бессмысленно, так как никакой регулярки нет... Можно написать просто 
```
if "/etc/init.d/" in line:
    # ...
```
Или лучше сделать регулярку на `/etc/init.d/<service_name> (start|stop|restart...)`.

2021-12-16 13:16 UTC, fe7ch commented on src/cowrie/shell/honeypot.py
> +        r = re.search(r"\/etc\/init\.d\/", line)
если проверять строку, тогда уж `line.startswith('')`, чтобы гарантированно в начале было.

Проверять команду (start/stop/restart) надо отдельно и выводить usage, если левак написан (посмотрите для конкретного сервиса, какие команды он принимает)

2021-12-16 13:21 UTC, crazylazyowl commented on src/cowrie/shell/honeypot.py
> +        r = re.search(r"\/etc\/init\.d\/", line)
Смысл в том, чтобы `/etc/init.d/<service> <cmd>` прировнять к `command/service.py`.
Поэтому просто логируем оригинал, а для дальнейшей эмулции команды корректируем её. Как и в старых костялых...
Всякие usage и прочее уже лежат на `command/service.py`.

Я пока не оч понял, может ли коврии обработать запуск скрипта хранящегося в фейковой фс.
Если да, то можно было бы создать файлик `/etc/init.d/iptables` и окей.

2021-12-16 13:23 UTC, gglchrm commented on src/cowrie/shell/honeypot.py
> +        r = re.search(r"\/etc\/init\.d\/", line)
понял принял исполнил

2021-12-20 13:47 UTC, gglchrm commented on src/cowrie/test/xaa
> +[A[B
done.

2021-12-20 18:54 UTC, crazylazyowl approved these changes

2021-12-21 05:54 UTC, fe7ch approved these changes

2021-12-21 05:55 UTC, merged